server:
  port: '8083'
spring:
  application:
    name: ride-sharing-service
  config:
    import: configserver:http://localhost:8086
  datasource:
    url: jdbc:mysql://localhost:3306/rideShare
    password: Kajal@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root