spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  application:
    name: ride-sharing-service
  datasource:

    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Welcome@1
    url: jdbc:mysql://localhost:3306/ridesharingservice
eureka:
  instance:
    prefer-ip-address: 'true'
  client:
    register-with-eureka: 'true'
    fetch-registry: 'true'
    eureka-service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: '8083'

