server:
  port: '8087'
spring:
  application:
    name: authentication-service
  config:
    import: configserver:http://localhost:8086
  datasource:
      url: jdbc:mysql://localhost:3306/userservice