spring:
  application:
    name: admin-service
  config:
    import: configserver:http://localhost:8086

eureka:
  client:
    register-with-eureka: 'true'
    fetch-registry: 'true'
    eureka-service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: 'true'
server:
  port: '8088'