server:
  port: 8084

spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://localhost:8086
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**

        - id: ride-sharing-service
          uri: lb://ride-sharing-service
          predicates:
            - Path=/api/rides/**

        - id: rental-service
          uri: lb://rental-service
          predicates:
            - Path=/api/rentals/**
