server:
  port: 8084

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: rental-service
          uri: lb://rental-service
          predicates:
            - Path=/api/rentals/**
        - id: ride-sharing-service
          uri: lb://ride-sharing-service
          predicates:
            - Path=/api/rides/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
